### ISSUE TITLE
The wrapper for Faker.generate seems to require a locale parameter

### ISSUE THREAD

**Issue by allynt** [FactoryBoy/factory_boy#788]
#### Description
An error is generated whenever I manually generate values from `factory.Faker`:

```
    def generate(self, params):
>       locale = params.pop('locale')
E       KeyError: 'locale'
```
In some cases, I can explicitly add a `locale` argument.  But when the `generate` fn is called from w/in Factory-Boy itself, I cannot.  For an example, consider the `factory.Maybe` statement in the following code:

##### Model / Factory code
```python
import factory
from django.db import models

class MyModel(models.Model):
    name = models.CharField(max_length=100)
    price = models.PositiveIntegerField()
    is_cheat = models.BooleanField()

class MyModelFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = MyModel
    name = factory.Faker("name")
    is_cheap = factory.Faker("boolean")
    price = factory.Maybe("is_cheap", yes_declaration=factoryFaker("pyint", max_value=10), no_declaration=factory.Faker("pyint", min_value=100))
   
```

##### The issue

```python
>>>MyModelFactory()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/.virtualenvs/foobar/lib/python3.7/site-packages/factory/base.py", line 39, in __call__
    return cls.create(**kwargs)
  File "/home/.virtualenvs/foobar/lib/python3.7/site-packages/factory/base.py", line 527, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "/home/.virtualenvs/foobar/lib/python3.7/site-packages/factory/django.py", line 117, in _generate
    return super()._generate(strategy, params)
  File "/home/.virtualenvs/foobar/lib/python3.7/site-packages/factory/base.py", line 464, in _generate
    return step.build()
  File "/home/.virtualenvs/foobar/lib/python3.7/site-packages/factory/builder.py", line 276, in build
    step.resolve(pre)
  File "/home/.virtualenvs/foobar/lib/python3.7/site-packages/factory/builder.py", line 217, in resolve
    self.attributes[field_name] = getattr(self.stub, field_name)
  File "/home/.virtualenvs/foobar/lib/python3.7/site-packages/factory/builder.py", line 382, in __getattr__
    extra=context,
  File "/home/.virtualenvs/foobar/lib/python3.7/site-packages/factory/declarations.py", line 526, in evaluate
    extra=extra,
  File "/home/.virtualenvs/foobar/lib/python3.7/site-packages/factory/declarations.py", line 356, in evaluate
    return self.generate(extra)
  File "/home/.virtualenvs/foobar/lib/python3.7/site-packages/factory/faker.py", line 46, in generate
    locale = params.pop('locale')
KeyError: 'locale'

```

#### Notes

I believe the issue is related to this code [[factory/faker.py#L45-L48](https://github.com/FactoryBoy/factory_boy/blob/a9c9aa82e62ef60bba01aa5366b1814ab8e12266/factory/faker.py#L45-L48)]:

```
    def generate(self, params):
        locale = params.pop('locale')
        subfaker = self._get_faker(locale)
        return subfaker.format(self.provider, **params)
```

replacing it w/ `locale = params.pop('locale', None)` effectively handles the case where locale is not explicitly provided.

**Comment by allynt** [comment]
After all that, it seems that somebody has already caught this and suggested the exact same fix: https://github.com/FactoryBoy/factory_boy/pull/785

**Comment by rbarrois** [comment]
Fixed through #828! Sorry for the long wait :/

**Comment by emilte** [comment]
I still struggle with this. `factoryboy==3.2.1` and `faker==13.14.0`

**Comment by radohristov** [comment]
Seems still not fixed:

factoryboy==3.2.1 and faker==13.15.0

    @pytest.fixture
    def unique_dominant_factors():
>       return list(set(DominantFactorsFactory.create_batch(3)))

tests/repositories/test_portfolio_values_per_dominant_factors_repository.py:14:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.tox/py3/lib/python3.10/site-packages/factory/base.py:540: in create_batch
    return [cls.create(**kwargs) for _ in range(size)]
.tox/py3/lib/python3.10/site-packages/factory/base.py:540: in <listcomp>
    return [cls.create(**kwargs) for _ in range(size)]
.tox/py3/lib/python3.10/site-packages/factory/base.py:528: in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
.tox/py3/lib/python3.10/site-packages/factory/base.py:465: in _generate
    return step.build()
.tox/py3/lib/python3.10/site-packages/factory/builder.py:258: in build
    step.resolve(pre)
.tox/py3/lib/python3.10/site-packages/factory/builder.py:199: in resolve
    self.attributes[field_name] = getattr(self.stub, field_name)
.tox/py3/lib/python3.10/site-packages/factory/builder.py:344: in __getattr__
    value = value.evaluate_pre(
.tox/py3/lib/python3.10/site-packages/factory/declarations.py:477: in evaluate_pre
    choice = self.decider.evaluate(instance=instance, step=step, extra={})
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <factory.faker.Faker object at 0x7fb44bb5dba0>
instance = <Resolver for <BuildStep for <StepBuilder(<FactoryOptions for DominantFactorsFactory>, strategy='create')>>>
step = <BuildStep for <StepBuilder(<FactoryOptions for DominantFactorsFactory>, strategy='create')>>, extra = {}

    def evaluate(self, instance, step, extra):
>       locale = extra.pop('locale')
E       KeyError: 'locale'

.tox/py3/lib/python3.10/site-packages/factory/faker.py:46: KeyError

**Comment by francoisfreitag** [comment]
See #965
